name: Github Output Test

on: push

permissions:
  contents: read

jobs:
  output-test:
    runs-on: ubuntu-latest
    steps:
    - id: 'summarytest'
      name: 'summary test'
      shell: bash
      run: |
        echo $GITHUB_OUTPUT
        printf "hi\n" >> $GITHUB_WORKSPACE/test.txt
        cat $GITHUB_WORKSPACE/test.txt
        cat $GITHUB_WORKSPACE/test.txt >> $GITHUB_OUTPUT
