name: Github Output Test

on: push

permissions:
  contents: read

jobs:
  output-test:
    runs-on: ubuntu-latest
    steps:
    - id: 'summarytest'
      name: 'summary test'
      shell: bash
      run: |
        echo "my-env-var='i love bitovi'" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

    - id: 'summarytest2'
      name: 'summary test 2'
      shell: bash
      run: |
        cat $GITHUB_OUTPUT
        echo $my-env-var